<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CryptoPluginAdapter</AssemblyName>
    <RootNamespace>CryptoPluginAdapter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lab3Serialization.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Lab5CryptoPlugin\Lab5CryptoPlugin.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <Target Name="DeployCryptoPluginAdapter" AfterTargets="Build">
    <PropertyGroup>
      <_PluginsDir>$(MSBuildProjectDirectory)\..\bin\$(Configuration)\net8.0-windows\Plugins\</_PluginsDir>
    </PropertyGroup>
    <MakeDir Directories="$(_PluginsDir)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(_PluginsDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
