<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FileHeaderPlugin</RootNamespace>
    <AssemblyName>FileHeaderPlugin</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lab3Serialization.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <Target Name="DeployPipelinePlugin" AfterTargets="Build">
    <PropertyGroup>
      <_HostPluginsDir>$(MSBuildProjectDirectory)\..\bin\$(Configuration)\net8.0-windows\Plugins\</_HostPluginsDir>
    </PropertyGroup>
    <MakeDir Directories="$(_HostPluginsDir)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(_HostPluginsDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
